# Build customization
builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X github.com/martensson/tpm/cmd.version={{.Version}} -X github.com/martensson/tpm/cmd.commit={{.Commit}} -X github.com/martensson/tpm/cmd.date={{.Date}}
# Archive customization
archive:
  format: tar.gz
  files:
    - LICENSE
  format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: martensson
    name: tpm-tap
  folder: Formula
  homepage: "https://github.com/martensson/tpm"
  description: "A CLI client to search and manage passwords inside TeamPasswordManager."
