language: go
go:
  - 1.7
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username martensson --token $GITHUB_TOKEN --replace --debug $TRAVIS_TAG dist/
